/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rmcar' at '2018-11-24 21:37' with Gradle 2.9
 *
 * @author rmcar, @date 2018-11-24 21:37
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
